# Generated by Django 5.1.4 on 2024-12-10 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('price', models.IntegerField(null=True)),
                ('image', models.ImageField(upload_to='bookMedia')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myBook.tbl_author')),
            ],
        ),
    ]
