# Generated by Django 5.1.4 on 2024-12-12 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBook', '0002_alter_tbl_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_book',
            name='quandity',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
    ]
