# Generated by Django 5.1.4 on 2024-12-13 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AccountsApp', '0002_logintable_remove_userprofile_type'),
        ('userapp', '0002_alter_cart_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginTable',
        ),
        migrations.DeleteModel(
            name='userProfile',
        ),
    ]
